"""FLUX-enabled Gradio Interface"""
import gradio as gr
from src.pipeline import Key2PosterPipeline
import time

print("Loading FLUX pipeline...")
pipeline = Key2PosterPipeline(
    use_flux=True,
    add_title=True,
    genre_lora=True,
    remove_text=False,
    super_resolution=False
)
print("✓ FLUX ready!")

def generate(keywords, poster_type, style_preset, seed):
    try:
        keyword_list = [k.strip() for k in keywords.split() if k.strip()]
        if len(keyword_list) < 2 or len(keyword_list) > 5:
            return None, f"❌ Provide 2-5 keywords (got {len(keyword_list)})"
        
        start = time.time()
        
        # Update style preset and poster type
        pipeline.style_preset = style_preset
        pipeline.poster_type = poster_type
        
        image, brief, metrics = pipeline.generate_poster(
            keywords,
            output_path=f"outputs/flux_{int(time.time())}.png",
            seed=seed if seed > 0 else None
        )
        elapsed = time.time() - start
        
        info = f"""
✅ **Generated in {elapsed:.1f}s**

**Model:** FLUX.1-schnell with text generation
**Poster Type:** {poster_type.title()}
**Style:** {style_preset.title()}
**Genre:** {getattr(pipeline, '_current_genre', 'N/A')}
**Sentiment:** {brief['sentiment']} ({brief['confidence']:.0%})
**Aesthetic:** {metrics['aesthetic']['overall']:.3f}

**Text:** Generated by FLUX (not PIL overlay)
"""
        return image, info
        
    except Exception as e:
        return None, f"❌ Error: {str(e)}"

demo = gr.Interface(
    fn=generate,
    inputs=[
        gr.Textbox(
            label="Keywords (2-5 words)",
            placeholder="cyberpunk neon city",
            lines=2
        ),
        gr.Dropdown(
            choices=["movie", "advertise", "event", "education", "social", "music", "sports"],
            value="movie",
            label="Poster Type"
        ),
        gr.Dropdown(
            choices=["cinematic", "minimalist", "neon", "dark", "vintage", "bright", "professional"],
            value="cinematic",
            label="Style Preset"
        ),
        gr.Number(label="Seed (0 = random)", value=0, precision=0)
    ],
    outputs=[
        gr.Image(label="Generated Poster", height=600),
        gr.Markdown(label="Info")
    ],
    title="🎨 Key2Poster FLUX",
    description="""
    Generate posters using FLUX.1-schnell with FLUX text generation.
    
    **Features:** FLUX Model • Multiple Poster Types • Style Presets • FLUX Text Generation
    
    **Poster Types:** Movie, Advertise, Event, Education, Social, Music, Sports
    """,
    examples=[
        ["space exploration adventure", "movie", "cinematic", 42],
        ["summer music festival", "event", "bright", 123],
        ["healthy eating habits", "education", "professional", 456],
        ["save the ocean", "social", "minimalist", 789],
    ],
    theme=gr.themes.Soft(),
    allow_flagging="never"
)

if __name__ == "__main__":
    demo.launch(share=False)
